### ISSUE TITLE
Handling content outside the map directory: incorrect links in nav toc

### ISSUE THREAD

**Issue by PieterjanVandenweghe** [infotexture/dita-bootstrap#201] opened 2024-05-24 15:15 UTC
When I work with content outside the map directory and I set the parameter _generate.copy.outer_ to 3, the nav-toc (collapsible in my case) in the output does not take this into account resulting in incorrect links.

Creating a default HTML5 output does not have this problem.

I attached a small sample map.
[sample_map.zip](https://github.com/infotexture/dita-bootstrap/files/15436515/sample_map.zip)

**Comment by PieterjanVandenweghe** [comment] 2024-05-29 08:51
I did some further testing and this is a general HTML5 plug-in problem. I will log it in the dita-ot repo.

**Comment by infotexture** [comment] 2024-06-02 16:01
@PieterjanVandenweghe Thanks for reporting this, and for verifying that it also occurs in the default HTML5 output. 

Since the problem isn't specific to the DITA Bootstrap plug-in, I'll close this issue and link to https://github.com/dita-ot/dita-ot/issues/4478.

**Closed by infotexture** 2024-06-02 16:01 UTC
