### ISSUE TITLE
net.infotexture.dita-bootstrap doesn't enable html5-bootstrap, on dita 4.1

### ISSUE THREAD

**Issue by SmartLayer** [infotexture/dita-bootstrap#96] opened 2023-07-16 22:23 UTC
In my old DITA-OT version 3.7.0, net.infotexture.dita-bootstrap was used to enable html5-bootstrap

now using dita-ot 4.1, 

```
$ dita --project config/my-site.yaml 
Error: [DOTA001F][FATAL] "html5-bootstrap" is not a recognized transformation type. Supported transformation types are dita, eclipsehelp, html5, htmlhelp, markdown, markdown_gitbook, markdown_github, pdf, pdf2, xhtml.
$ dita install net.infotexture.dita-bootstrap
Error: Plug-in fox.jason.extend.css already installed: /opt/dita-ot-4.1/plugins/fox.jason.extend.css
```
The plugin is clearly installed, but the transtype "html5-bootstrap" is missing.
````
$ dita plugins | grep bootstrap
net.infotexture.dita-bootstrap@5.3.2
$ dita --transtypes
pdf
xhtml
eclipsehelp
html5
htmlhelp
dita
pdf2
markdown
markdown_github
markdown_gitbook
````

I reported a similar problem a few years ago as #31 

However, the workaround posted in that issue didn't work for 4.1:

```
$ dita uninstall net.infotexture.dita-bootstrap
Error: Plug-in /opt/dita-ot-4.1/plugins/net.infotexture.dita-bootstrap doesn't exist.
$ dita install net.infotexture.dita-bootstrap
Error: Plug-in fox.jason.extend.css already installed: /opt/dita-ot-4.1/plugins/fox.jason.extend.css
$ dita --project config/my-site.yaml 
Error: [DOTA001F][FATAL] "html5-bootstrap" is not a recognized transformation type. Supported transformation types are dita, eclipsehelp, html5, htmlhelp, markdown, markdown_gitbook, markdown_github, pdf, pdf2, xhtml.
```

This is a completely new computer with no prior dita installed on it.
````
$ uname -a
Linux weiwu-21BXCTO1WW 6.2.0-1005-laptop #6-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 16:47:31 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
$ java --version
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu123.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu123.04, mixed mode, sharing)
````

My current suspicion is that the plugin dependency auto-handling code erred, evident by `dita install net.infotexture.dita-bootstrap` led a message that a *different* plugin is installed.

**Comment by infotexture** [comment] 2023-07-18 08:53
🧐 There seems to be something peculiar about the way you're installing and/or removing these plug-ins, as we haven't similar issues from others.

(There's a typo in the `uninstall` command at https://github.com/TokenScript/documents/commit/4c92bf45e9b53827267ecb23252e24261f89e1d0, but I'm not sure if that's the source of the problems here.)

You say:

> This is a completely new computer with no prior dita installed on it.

but the error messages suggest there are remnants of earlier plug-in installations.

I suggest you try removing any corresponding plug-in folders from the `plugins` subdirectory of your DITA-OT installation and re-running the `dita install` command (with no arguments) to reload the current set of plug-ins from the `plugins` directory as described in https://www.dita-ot.org/dev/topics/plugins-installing.html.

That should respond by listing any changes to the current plug-in configuration, and return you to a clean starting point.

**Comment by weiwu-zhang** [comment] 2023-07-18 10:03
> You say:
> 
> > This is a completely new computer with no prior dita installed on it.
> 
> but the error messages suggest there are remnants of earlier plug-in installations.

This aroused much of my interest to see first hand, a newly installed computer, when installing plugin, says that something in existence, This is why I said this:

> My current suspicion is that the plugin dependency auto-handling code erred, evident by dita install net.infotexture.dita-bootstrap led a message that a different plugin is installed.

My theory is that

1. when installing the first plugin the first time, it found some dependency
2. It installed that dependency, let's say A
3. then it look for a second dependency, attempt to install it, let's say B.
4. B depends on A, so it goes on to install A, unaware that it is already installed
5. Erred.

I can reproduce this the same way I reproduced it with my last computer which retired. As of today, I discovered the workaround:

$ dita uninstall net.infotexture.dita-bootstrap
$ dita uninstall fox.jason.favicon
$ dita uninstall fox.jason.extended.css
$ dita install fox.jason.extend.css
$ dita install fox.jason.favicon
$ dita install net.infotexture.dita-bootstrap

Note that in this workaround, the order of installation must be precise. Attempting to install net.infotexture.dita-bootstrap before 
fox.jason.extend.css seem to lead to fox.jason.extend.css being installed but net.infotexture.dita-bootstrap couldn't work any more. The order must be exactly as is, fox.jason.extend.css -> fox.jason.favicon -> net.infotexture.dita-bootstrap

You can close this issue if you consider the workaround enough proof that the software is okay. But if you are willing to dig, I will ask a colleague to start from scratch and attempt the same and see the result. I can guarantee the colleague I choose is the one who never installed dita on his PC and to compare the result.

**Comment by infotexture** [comment] 2023-09-24 11:56
> the order of installation must be precise

In the installation instructions, we recommend installing the plug-ins in that order, so I think we can close this:

```
dita install fox.jason.extend.css
dita install net.infotexture.dita-bootstrap
```

**Closed by infotexture** 2023-09-24 11:56 UTC
