### ISSUE TITLE
Displaying issue for topics at level 3 and more

### ISSUE THREAD

**Issue by Nico-Amplexor** [infotexture/dita-bootstrap#56] opened 2022-09-29 11:00 UTC
Hello,

I founded a displaying issue with topics at level 3 and more : 

![image](https://user-images.githubusercontent.com/37327034/193012789-b41ec37b-7393-4438-bf88-3692ef5bd17c.png)

Used command line:
`dita -i "C:\xxx\inputs\flowers\flowers.ditamap" -t "C:\xxx\inputs\flowers\temp" -o "C:\xxx\inputs\flowers\out" -f=html5-bootstrap -v --menubar-toc.include=no --args.breadcrumbs=yes --nav-toc=collapsible`

Input and output are here:
[flowers.zip](https://github.com/infotexture/dita-bootstrap/files/9673974/flowers.zip)

Thanks.

**Comment by jason-fox** [comment] 2022-09-29 19:26
Can you confirm you are running this on the latest DITA-Bootstrap [5.3.2 release](https://github.com/infotexture/dita-bootstrap/releases/tag/5.3.2) with the latest extend.css [v1.2.0](https://github.com/jason-fox/fox.jason.extend.css/tree/v1.2.0) ? When I run your transform my arrows expand properly as shown below. I also don't get any excessive whitespace - tested on Chrome and on Firefox.

<img width="746" alt="Screenshot 2022-09-29 at 21 05 24" src="https://user-images.githubusercontent.com/3439249/193120636-6b0906ed-c77a-4c35-bfd1-85a2270a0d26.png">

I noticed that in your output `common-extended.css` is failing to load - it is looking in the wrong place:

```diff
<link rel="stylesheet" type="text/css" href="../../css/commonltr.css">
- <link rel="stylesheet" type="text/css" href="../css/common-extended.css">
+ <link rel="stylesheet" type="text/css" href="../../css/common-extended.css">
```

My guess is that was a bug and fixed in `fox.jason.extend.css` at some point.

**Comment by jason-fox** [comment] 2022-09-30 11:00
That is really weird. I cannot reproduce your issue. I tried a local build on Mac and a GitHub Action build [here](https://jason-fox.github.io/test-dita-build/topics/introduction.html) and they both work fine. Maybe it is a Windows issue of some sort?

**Comment by Nico-Amplexor** [comment] 2022-09-30 11:52
You are right. It's a Windows specific issue. 
I tried the same transformation on Linux and it works well!

**Comment by jason-fox** [comment] 2022-09-30 17:01
This is guess work, but try reversing the slash [here](https://github.com/jason-fox/fox.jason.extend.css/blob/master/Customization/xsl/extended-css.xsl#L31)

```diff
- <xsl:value-of select=" replace($FILEDIR,'[^/]+','..')"/>
+ <xsl:value-of select=" replace($FILEDIR,'[^\]+','..')"/>
```

I'm guessing your `$FILEDIR` is not a linux style filepath.  Either way it is not a bug in **this plug in**, it is a bug in [the other one]((https://github.com/jason-fox/fox.jason.extend.css) = I don't use Windows.

**Comment by jason-fox** [comment] 2022-09-30 17:04
Moving issue to https://github.com/jason-fox/fox.jason.extend.css/issues/5

**Closed by jason-fox** 2022-09-30 17:04 UTC
