### ISSUE TITLE
Issues with chunked topics and TOC

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#102] opened 2023-08-09 17:35 UTC
Hi,

I'm working with the latest develop of the the plugin on DITA-OT 3.7.4 , and noticed this:

Using the chunk="to-content" attribute on a topic causes the default TOC and the breadcrumb component to be missing on the topic. See attached image: 

![image1](https://github.com/infotexture/dita-bootstrap/assets/108674366/526cf795-d474-4389-a193-436769177a78)

And for reference a topic that is not chunked:

![image2](https://github.com/infotexture/dita-bootstrap/assets/108674366/c3923b69-438c-44f6-8f1e-deb9897bdbc6)

(By the way, thank you so much for developing and maintaining this plugin! I think it's something the DITA community really needs: a good looking open source static site generator.)

**Comment by jason-fox** [comment] 2023-08-09 18:37
I can't reproduce that without more details. Using the the `flowers.ditamap` [here](https://github.com/jason-fox/test-dita-build/blob/master/flowers/flowers.ditamap#L17) I can obtain the following [Spring Flowers with a breadcrumb](https://jason-fox.github.io/test-dita-build/concepts/springFlowers.html)

**Comment by lakokkonen** [comment] 2023-08-09 19:39
Ok, I downloaded OT 3.7.3 and everything worked perfectly. I'm inclined to believe that the issue was that some other plugin that came bundled with the Oxygen OT messed things up somehow.

**Comment by infotexture** [comment] 2023-08-15 21:12
Closing this per previous comment.

**Closed by infotexture** 2023-08-15 21:12 UTC
Labels: invalid
