### ISSUE TITLE
html5-bootstrap

### ISSUE THREAD

**Issue by StanDoherty** [infotexture/dita-bootstrap#3] opened 2020-07-09 16:29 UTC
Hi Roger --
I installed html5-bootstrap in dita-ot-3.5.2. It successfully installed and successfully built docsrc/samples/hierachy.ditamap, yet the generated output (toc.html) seems to be generic DITA-OT HTML5 output. 

Were there some pre-requisites that I missed along the way?

I have attached the generated output.

Thanx,
Stan (stan@modularwriting.com)
 
[out.zip](https://github.com/infotexture/dita-bootstrap/files/4898103/out.zip)

**Comment by paperdigits** [comment] 2020-07-09 19:08
To get a proper index.HTML style landing page, I either have a file named index.dita or use copy-to to output some file as index.html. The ToC generation is indeed plain, but the ToC is in ever page, so the regular TOC.HTML is a bit useless.

**Comment by infotexture** [comment] 2020-12-19 18:17
@StanDoherty Sorry I missed this earlier, but Mica's right: the relevant portions of the `toc.html` file are embedded into each page by setting the [nav-toc](https://www.dita-ot.org/dev/parameters/parameters-html5.html#html5__nav-toc) parameter to `partial`, so you wouldn't typically use this as your landing page.

_(In this regard, the Bootstrap plug-in is no different from the default HTML5 output.)_

You'll need either an `index.dita` file at the top level of your project to use as a landing page, or use `copy-to` to rename the landing page topic to `index.html` when output is generated.

If you open any of the HTML files for the other topics, you'll see that the Bootstrap styles are correctly applied, so I'll close this issue, as it's working as intended.

**Closed by infotexture** 2020-12-19 18:17 UTC
