### ISSUE TITLE
Dark mode not working on topics in subfolders

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#141] opened 2023-11-15 09:29 UTC
Using the latest dev version of the plugin.

If a topic is located in a subfolder more than one level deep from the output directory, the dark mode toggler doesn't work on the HTML page. 

It looks like the path to the .js file is always **../js/dark-mode-toggler.js**, and of course that only works for pages that are located one folder deep. I believe the issue is in the **relpath** variable, but that's where my XSLT skills end in this case.

EDIT:

Actually now I got it working by changing the regex in the replace function: <xsl:value-of select=" replace($FILEDIR,'[^\\]+','..')"/>

But as a result the file path contains both forward and backslashes. Seems to work, however, both on local files and via an http server. 

EDIT 2:

I was able to switch the backslashes to forward ones with this monstrosity: <xsl:value-of select="translate( replace($FILEDIR,'[^\\]+','..'), '\\', '/' )"/>

**Comment by infotexture** [comment] 2023-11-19 17:03
@lakokkonen I can't reproduce this on macOS. The toggler works fine there regardless of hierarchy.

Are you running into this problem on Windows?

**Comment by lakokkonen** [comment] 2023-11-19 18:49
@infotexture Yes, I'm using Windows and local files. 

It seems like this issue stems from the Windows file path naming which uses backslashes.

**Comment by jason-fox** [comment] 2023-11-21 21:14
@lakokkonen - I think the following regex simplifies your fix and continues to work on Linux - could you check


```xml
<xsl:value-of select="replace(replace($FILEDIR, '\\', '/') ,'[^/]+','..')"/>
```

see #142

**Comment by lakokkonen** [comment] 2023-11-22 10:48
@jason-fox yes, now it's working on Windows.

**Comment by infotexture** [comment] 2023-11-22 21:36
Fixed by https://github.com/infotexture/dita-bootstrap/pull/142.

**Closed by infotexture** 2023-11-22 21:36 UTC
